### ISSUE TITLE
Add working directory option to launch program dialog.

### ISSUE THREAD

**Issue by daseyb** [pierricgimmig/orbitprofiler#1]
First of all: Amazing work, this looks great and has been working flawlessly in my (limited) test runs!

While it's not absolutely necessary it would be nice to be able to set the working directory of a program you launch via Orbit.

Cheers, Dario

**Comment by pierricgimmig** [comment]
Hi, thanks for your comment!  Good suggestion, it's an easy fix, I'll do that for the next version.  In case you didn't know, you don't necessarily have to launch a process from Orbit to start profiling, you can hook to a process that is already running.  The process launcher is there for the specific case where you need to profile program startup or global initialization before main is called.  Cheers!

**Comment by daseyb** [comment]
Yeah, it's definitely a very small issue, attaching Orbit to a running process works fine for me too and if not I can always move the executable to the working directory it needs to be started in :)

**Comment by pierricgimmig** [comment]
Fixed in https://github.com/pierricgimmig/orbitprofiler/commit/7bf2164aa892e6af1effeabe6d6985fd32bb66d4.  Released in version 1.0.1
