### ISSUE TITLE
Windows bootstrap should run external/vcpkg/bootstrap-vcpkg.bat

### ISSUE THREAD

**Issue by robbiesri** [pierricgimmig/orbitprofiler#140]
I was trying to update my Windows build, but I was having problems with vcpkg grabbing the packages it needed. After a bit of poking, I realized that my local vcpkg.exe was out of date, but bootstrap-orbit.bat didn't run the vcpkg bootstrap. It...should?

**Comment by beckerhe** [comment]
Hi Rob,
that's a good point.

Whenever the vcpkg submodule is updated (like it was last week), we might need to update vcpkg and all the dependencies it manages for us as well. I believe for updating the dependencies the `vcpkg update` command is the correct way to go. I'm not sure whether this also updates the vcpkg executable if necessary.

But apart from that a bigger question arises: Should we support "upgrades" in the bootstrapping process? Or should we only support clean builds? @pierricgimmig, what is your take on this?
I tend to only supporting clean builds (no preexisting vcpkg instance, no preexisting build directory)
and as far as I understood from https://github.com/pierricgimmig/orbitprofiler/issues/127 this is also your major use case, right?

We could just fail (with a error message) in the bootstrapping script if vcpkg.exe existed before and the same if a build directory existed.
Furthermore, we could add a `--force` option, which removed preexisting build directories and vcpkg installations. So "upgrading" would mean that either you have to go through a clean build (building all the dependencies etc.) or figuring out by yourself how to upgrade (calling `vcpkg update`, maybe deleting the CMakeCache.txt from the build directory, etc.)

Cheers,
Henning

**Comment by robbiesri** [comment]
I don't mind going through the clean process (well...) but depending on what the core build setup for this tool is, it should be made clear in README.md or DEVELOPMENT.md. If there is some expectation that developers would be iterating locally, then fast-forwarding a local branch should 'work' most of the time. On the other hand, if the expectation that every build should start from a fresh clone (aka, like on a build server), then...say that, and provide builds.

meta-comment: I know lots of stuff is going on here, but a couple weeks ago, I was able to build the Windows client in 20-30 minutes on my workstation. Last night, it took multiple hours, and didn't even succeed (failed somewhere with curl, I didn't have the energy to chase it up at the time).

**Comment by beckerhe** [comment]
> I don't mind going through the clean process (well...) but depending on what the core build setup for this tool is, it should be made clear in README.md or DEVELOPMENT.md. If there is some expectation that developers would be iterating locally, then fast-forwarding a local branch should 'work' most of the time. On the other hand, if the expectation that every build should start from a fresh clone (aka, like on a build server), then...say that, and provide builds.
Yes, and it will work. Updating vcpkg should not be necessary too often.
> 
> meta-comment: I know lots of stuff is going on here, but a couple weeks ago, I was able to build the Windows client in 20-30 minutes on my workstation. Last night, it took multiple hours, and didn't even succeed (failed somewhere with curl, I didn't have the energy to chase it up at the time).

Yeah, I see your point. This is basically my fault. We are trying to set up continuous integration. But for that to succeed we had to simplifiy the build process. I tried to test these changes on 4 different machines with at least 2 different build configurations each and still others found problems. I hope we can greatly improve here when CI is running. Hopefully this will be the case this or next week.

Regarding build times: One of the big changes was to handle the qt dependency via vcpkg to have a single source for our dependencies and to make it unnecessary to manually install qt5 on any (CI) machine. But this increases the build time a lot. vcpkg has the ability to export and import prebuilt binary packages but I haven't looked into that yet. If that works as promised, we might be able to export prebuilt dependency artifacts from our CI system and so to provide a faster (clean) build.

About your curl problem: Please just file a bug with the error message. I will be more than happy to look into this. The overall goal of these cmake and vcpkg changes were to get a more stable build system and all supported platforms, not the opposite.

Cheers,
Henning

**Comment by robbiesri** [comment]
I opened the issue, but as I started to poke around, I realized it was probably because of outdated vcpkg bits that were hanging around. But the bootstrap process doesn't upgrade them right now. Trying to go through a local upgrade to see if that works...

**Comment by robbiesri** [comment]
Ran `vcpkg upgrade`, which took an hour. But at least Orbit is building (didn't finish yet tho)

**Comment by beckerhe** [comment]
Since we moved away from vcpkg, I'm going to close this issue.
