### ISSUE TITLE
Remote capture crashes with stack unwinding errors

### ISSUE THREAD

**Issue by robbiesri** [pierricgimmig/orbitprofiler#145]
Now that I'm back up with the remote Linux server and local Windows client, I tried taking a capture. The remote service gives me some spew before crashing, followed by the local Windows client crashing:

```
void ConnectionManager::StartCaptureAsRemote() /mnt/developer/orbitprofiler/OrbitCore/ConnectionManager.cpp(117) TID: 139738275755968
Starting Capture::StartCapture...
void LinuxEventTracer::Start() /mnt/developer/orbitprofiler/OrbitCore/LinuxEventTracer.h(82) TID: 139738275755968
Capture::StartCapture took 0.422760 ms.
virtual void OrbitApp::StartRemoteCaptureBufferingThread() /mnt/developer/orbitprofiler/OrbitGl/App.cpp(174) TID: 139738275755968
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_INVALID_MAP at 0x007f7531e56ae0
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_INVALID_MAP at 0x007f75297f9ae0
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_MEMORY_INVALID at 0x007f7556ffc708
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_INVALID_MAP at 0x007f75df7fd918
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_INVALID_MAP at 0x007f75237fdae0
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_INVALID_MAP at 0x007f75297f9ae0
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_INVALID_MAP at 0x007f7531e56ae0
LibunwindstackUnwinder::Unwind: unwinding error: ERROR_MEMORY_INVALID at 0x007f751a7fb640
```

Repro'd with 1930c104e2fcdee96fa92a3759ae5e828872f53c

**Comment by pierricgimmig** [comment]
@dpallotti, have you seen that before?

**Comment by robbiesri** [comment]
This crashes with and without instrumented functions

**Comment by pierricgimmig** [comment]
I think the unwind errors are not fatal.  The actual crash was fixed in https://github.com/pierricgimmig/orbitprofiler/commit/cecef4b60fa6bbfebc9361bccbd3625c2b851e6b.  It should work on your side now @robbiesri .  Thanks for reporting this.

**Comment by dpallotti** [comment]
The Windows client is indeed not working at the moment and it even causes the remote server to crash. I'm starting to investigate this and quite a few fixes are necessary. The unwinding errors are unrelated as they only cause the callstack sample to be discarded.
