### ISSUE TITLE
Bootstrap not working on Windows after LLVM CL

### ISSUE THREAD

**Issue by pierricgimmig** [pierricgimmig/orbitprofiler#177]
Cloning the repo and running bootstrap-orbit.bat gives me:

CMake Error at external/vcpkg/scripts/buildsystems/vcpkg.cmake:285 (_find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

**Comment by dimitry-** [comment]
can you check vcpkg output - was it successfully installed? It sometimes ask for some additional components to be installed in Visual Studio - like MFC/ALT.

**Comment by pierricgimmig** [comment]
I did install the MFC/ATL dependencies in through the Visual Studio installer.  I don't have access to my Windows machine now, but I'll look closer at the logs.

Have you tried cloning and building from scratch by the way?

**Comment by pierricgimmig** [comment]
Looking at CMakeError.log, I have:

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/git/orbit_llvm/build_release_x64/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_5efa9.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  CheckIncludeFile.c

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5efa9.dir\Debug\\" /Fd"cmTC_5efa9.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue C:\git\orbit_llvm\build_release_x64\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  

C:\git\orbit_llvm\build_release_x64\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\git\orbit_llvm\build_release_x64\CMakeFiles\CMakeTmp\cmTC_5efa9.vcxproj]

**Comment by dimitry-** [comment]
This is really flaky - I have not seen this error on my windows workstation.
I am going to remove llvm from windows build for now.
