### ISSUE TITLE
Ubuntu build not working

### ISSUE THREAD

**Issue by pierricgimmig** [pierricgimmig/orbitprofiler#197]
With the latest Conan changes, running bootstrap-orbit.sh fails at the cmake "generate" step.

I get: 

```
-- Configuring done
CMake Error at OrbitGl/CMakeLists.txt:4 (add_library):
  Target "OrbitGl" links to target "OpenGL::OpenGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

I get the same when running "build.sh clang9_release" for example.

**Comment by beckerhe** [comment]
Hi Pierric,
I've made some changes to make GGP cross compilation work,
which might result in this behaviour.

Tomorrow I'm going to remove these hacks and verify that cross compilation still works.

Can you provide the version of Ubuntu you tried this on? I'm going to reproduce this as well.

**Comment by pierricgimmig** [comment]
Great, thanks for looking into this.  Here's my Ubuntu version:

pierric@buntu:~$ uname -r
5.3.0-40-generic
pierric@buntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

**Comment by beckerhe** [comment]
Thanks.

I haven't managet yet to reproduce it. When I try to compile Orbit in a Ubuntu 19.10 docker container, it works just fine.

Just for reference, I tried this:
docker run -it --rm ubuntu:eoan
> export PATH=$HOME/.local/bin:$PATH
> apt update
> apt install -y git sudo
> cd
> git clone https://github.com/pierricgimmig/orbitprofiler.git
> cd orbitprofiler/
> ./bootstrap-orbit.sh

I'm going to clean up the OpenGL hacks. Let's see if that helps.

**Comment by beckerhe** [comment]
Just a random idea: Do you have some "special" graphics driver installed?
The nvidia binary driver for example?

**Comment by beckerhe** [comment]
Hi Pierric,
I'm still trying to figure out where this is coming from. It would be great, if you could provide the output of `grep OPENGL_ CMakeCache.txt`.

Thanks,
Henning

**Comment by pierricgimmig** [comment]
Hi Henning, thanks for the ping.  Here's the output:

OPENGL_EGL_INCLUDE_DIR:PATH=/usr/include
OPENGL_GLX_INCLUDE_DIR:PATH=/usr/include
OPENGL_INCLUDE_DIR:PATH=/usr/include
OPENGL_egl_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libEGL.so
OPENGL_gl_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libGL.so
OPENGL_glu_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libGLU.so
OPENGL_glx_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libGLX.so
OPENGL_opengl_LIBRARY:FILEPATH=OPENGL_opengl_LIBRARY-NOTFOUND
OPENGL_xmesa_INCLUDE_DIR:PATH=OPENGL_xmesa_INCLUDE_DIR-NOTFOUND
//ADVANCED property for variable: OPENGL_EGL_INCLUDE_DIR
OPENGL_EGL_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_GLX_INCLUDE_DIR
OPENGL_GLX_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_INCLUDE_DIR
OPENGL_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_egl_LIBRARY
OPENGL_egl_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_gl_LIBRARY
OPENGL_gl_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_glu_LIBRARY
OPENGL_glu_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_glx_LIBRARY
OPENGL_glx_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_opengl_LIBRARY
OPENGL_opengl_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: OPENGL_xmesa_INCLUDE_DIR
OPENGL_xmesa_INCLUDE_DIR-ADVANCED:INTERNAL=1

**Comment by pierricgimmig** [comment]
Concerning the graphics driver, I have an amd gpu, heres the output of "lshs -c video":

pierric@buntu:~/git/orbitprofiler/build_default_release$ lshw -c video
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:49 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:f7e00000-f7e3ffff memory:c0000-dffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.


pierric@buntu:~/git/orbitprofiler/build_default_release$ modinfo amdgpu
filename:       /lib/modules/5.3.0-40-generic/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko
license:        GPL and additional rights
description:    AMD GPU
author:         AMD linux driver team
...

**Comment by pierricgimmig** [comment]
I just retested it after cloning the repo.  See the full command output here: https://gist.github.com/pierricgimmig/f64c96e986bddd1374e333d88dbc35fd

**Comment by pierricgimmig** [comment]
Commenting this block fixes the issue:

```
# if(TARGET OpenGL::GLX AND WITH_GUI)
#   target_link_libraries(OrbitGl PUBLIC OpenGL::GLX)
# endif()
```

**Comment by beckerhe** [comment]
Hi Pierric,
can you check whether this works? https://github.com/pierricgimmig/orbitprofiler/pull/230

Thanks,
Henning

**Comment by pierricgimmig** [comment]
Hi Henning, I tested it and it works! Thanks for the fix!
