### ISSUE TITLE
Download speed of prebuilt application is slow

### ISSUE THREAD

**Issue by donalmacc** [pierricgimmig/orbitprofiler#2]
I realise this isn't necessarily the best place for this, but the download linked on [this page](http://www.telescopp.com/update) is limited to ~400kbps. It could be hosted as a [github release](https://help.github.com/articles/creating-releases/) - which for me is an instant download on a file 5 times the size

**Comment by pierricgimmig** [comment]
Good point, thanks!  I'll switch to github release soon.  Cheers

**Comment by pierricgimmig** [comment]
https://github.com/pierricgimmig/orbitprofiler/releases
