### ISSUE TITLE
can't profile my application

### ISSUE THREAD

**Issue by RicoP** [pierricgimmig/orbitprofiler#3]
I would like to profile my project, but after loading my project and the pdb file nothing show up in the right hand side of the screen.

**Comment by pierricgimmig** [comment]
Are you able to right click on a particular pdb in the "modules" view and load it as shown in this video: http://telescopp.com/howto ?

The pdb files must have the same name as their associated compiled modules (unreal.exe->unreal.pdb, physx.dll->physx.pdb, etc.).  Also, the pdb files must live next to their associated modules.

**Comment by RicoP** [comment]
Ok, I think I found my mistake. I had to go into the project settings and change under Linker->Debugging the point 'Generate Debug Info' from /DEBUG to /DEBUG:FULL

![image](https://user-images.githubusercontent.com/162828/30874156-d721a810-a2ef-11e7-9af2-2c6e33006eca.png)

With the simple /DEBUG orbit simply wont do anything.
