### ISSUE TITLE
Is not Win-10 compatible? I am not able to launch it in Win-10 machines.

### ISSUE THREAD

**Issue by SBarik007** [pierricgimmig/orbitprofiler#35]

**Comment by pierricgimmig** [comment]
Orbit is developed and tested on Windows 10...  What are you experiencing exactly?  Orbit requires administrator privileges to run, could this be the issue?

**Comment by SBarik007** [comment]
Yes that was the issue.In my system it is restricting me to launch the application due to some reason,but I am able to launch the application in other system.So may be some firewall settings in my system has to be changed.Thanks for the prompt reply.And one more question is this tool going to capture the methods that are being called when I perform a certain workflow?

**Comment by pierricgimmig** [comment]
Ok thanks for the update.  I noticed that windows started prompting me "Windows Defender SmartScreen prevented an unrecognized app from starting".  If that happens, you need to click on "more info" and "Run anyway".  I'll see what I can do to get Orbit recognized as a trusted app by Microsoft.

To answer your question, yes, absolutely.  The main goal of Orbit is to tell you what's happening in your application.  It does so by sampling but also by dynamically instrumenting functions of interest.  Sampling is always on.  However, you'll have to select the functions you want to dynamically instrument from the "functions" tab after having loaded the pdb file.  ( see http://telescopp.com/howto )

**Comment by SBarik007** [comment]
Ok thanks.I will try the feature.
