### ISSUE TITLE
not works

### ISSUE THREAD

**Issue by Karaulov** [pierricgimmig/orbitprofiler#37]
Windows 10 x64

Tried to profile 32 bit process.

NOTHING WORKS! 

(Works only if uses 'stop at entry point')

But i need profile process after start! And after load all symbols.

**Comment by Karaulov** [comment]
@pierricgimmig i tried to select my process but got unknown!

And orbit wrote '64bit' process, but this process 32bit!

**Comment by Karaulov** [comment]
And even i can select my process, 'X' hotkey not works after found all symbols....

**Comment by Karaulov** [comment]
how to download latest build from ci.appveyor.com ?(((

**Comment by pierricgimmig** [comment]
Duplicate of https://github.com/pierricgimmig/orbitprofiler/issues/38
