### ISSUE TITLE
UI Lag when connected to headless service

### ISSUE THREAD

**Issue by robbiesri** [pierricgimmig/orbitprofiler#40]
When playing with the new headless mode, I found that there is a fair amount of UI lag from input to something happening on screen. It's not consistent, and most of the time, it's quite responsive. But quite regularly, input processing seems to hang for about a second.

After poking around, I found that this only happens when the UI client is connected to a remote service. If I start the client without an active connection, the UI is very snappy. If I have it connected to a remote service, without even having started any profiling actions, the UI will lag.

Video of issue: https://photos.app.goo.gl/CTj2UhbkoTtba4ou5

**Comment by robbiesri** [comment]
This was built with QT 5.12.5, on Win10 x64.

**Comment by pierricgimmig** [comment]
Thanks for filing the issue.  

It should be improved by 

https://github.com/pierricgimmig/orbitprofiler/commit/78e75b424e991a1262f29d2b45a5150bd0f7aaa8

Every time we would receive a remote list of processes, we'd spend ~200 ms on the main refreshing the list of local processes, which we don't need to do at all.  Leaving this open as a there is still room for improvement.  Basically, work currently done on the main thread when receiving a remote process list should be offloaded.

**Comment by robbiesri** [comment]
I just tried it out, and the performance feels just as good as local now! Feels incredible to use!
Really huge improvement, thanks so much for the quick turnaround!

**Comment by pierricgimmig** [comment]
Great!  Thanks for testing!
