### ISSUE TITLE
Linux/remote does not show context switching/CPU scheduling information

### ISSUE THREAD

**Issue by robbiesri** [pierricgimmig/orbitprofiler#49]
Not sure if this is being tracked anywhere already, but the context switch info (present in the Windows version) would be very useful for tracking how process threads get scheduled on the CPUs.

**Comment by pierricgimmig** [comment]
Definitely high on the priority list!  Thanks for logging.

**Comment by florian-kuebler** [comment]
Linux version is fixed, remote version should be fixed by #90
