### ISSUE TITLE
Use actual AppData directory instead of SystemDrive for app data

### ISSUE THREAD

**Issue by mihe** [pierricgimmig/orbitprofiler#5]
I noticed that I was getting a folder named `OrbitProfiler` at the root of my `C:` drive after launching Orbit. After looking through [the source code](https://github.com/pierricgimmig/orbitprofiler/blob/cead6279ae4b230bc7d9f339197661b919ff8025/OrbitCore/Path.cpp#L254-L260) it seems like this was intentional. This is usually considered poor form, and I would appreciate if you would make use of [the actual](https://stackoverflow.com/a/11032792) `%APPDATA%` directory instead (`CSIDL_APPDATA` instead of `CSIDL_COMMON_APPDATA`).

**Comment by pierricgimmig** [comment]
You are absolutely right, I'll fix that for the next version.  Thank you.

**Comment by pierricgimmig** [comment]
Fixed in https://github.com/pierricgimmig/orbitprofiler/commit/7bf2164aa892e6af1effeabe6d6985fd32bb66d4.  Released in version 1.0.1
