### ISSUE TITLE
Handling long names in capture view

### ISSUE THREAD

**Issue by robbiesri** [pierricgimmig/orbitprofiler#54]
Sometimes, the instrumented functions have _very_ long names (usually because of namespaces). Sometimes the long names don't fit in the instrumented function view, and sometimes they crowd out the time spent in the instrumented function. 

Some ideas, not exclusive:
- Multi-line display of instrumented functions. Could be tied to the vertical zoom feature.
- Always show the time, and clip the function name
- Full function-name pops up as hover text

**Comment by robbiesri** [comment]
I started to snoop around TimeGraph::UpdatePrimitives to see how text gets rendered for the timers. I started to play around with the text rendering a bit. A couple implementation ideas if it should stay single-line

-  Change the ordering of printed info from (name, extraInfo, time) to (time, name, extraInfo)
-  Add some version of TextRenderer::AddText that prioritized rendering the last N letters of a string (aka, the time)...

**Comment by pierricgimmig** [comment]
Those are good suggestions, thanks @robbiesri.  Hovering works already on Windows, I'll see why this is broken the case of a remote Linux capture.  I agree that the most useful information is usually time and should be prioritized.  Implementing proper text ellipsis should also be done.  Also, soon we'll be able to click on an event and get the full information displayed in a subsection of the capture view without having to zoom in on the event.

**Comment by robbiesri** [comment]
Oh coool! I've been working on the 'ellipsis' view myself actually, because...I can't just be asking for stuff constantly without helping out a bit myself. I'll try to get a PR out, but maybe it'll be subsumed by some of the other functionality.

**Comment by pierricgimmig** [comment]
Oh great, it will definitely be useful, please do!

**Comment by pierricgimmig** [comment]
Hovering should now work properly (https://github.com/pierricgimmig/orbitprofiler/commit/7282871478890b485223714e08e28065d1f40832)

**Comment by robbiesri** [comment]
Thanks verified it! Will try to get that PR out...soonish

**Comment by florian-kuebler** [comment]
This seems to be fixed and should be closed.

**Comment by pierricgimmig** [comment]
Fixed in "headless" branch (https://github.com/pierricgimmig/orbitprofiler/pull/64).  Thanks Rob!!
