### ISSUE TITLE
Built-from-source version always notifies of version update

### ISSUE THREAD

**Issue by vvuk** [pierricgimmig/orbitprofiler#7]
The notification window always pops up... should probably ignore the version check if the version is `dev` :)

**Comment by pierricgimmig** [comment]
:-)  Will get fixed ASAP, thanks!

**Comment by pierricgimmig** [comment]
Fixed: 
 https://github.com/pierricgimmig/orbitprofiler/commit/fcc6c64de78e1db5ef29781397aaeea5487eb306
